# Generated by Django 3.2.24 on 2024-02-18 22:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('fecha_registro', models.DateField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('feha_creacion', models.DateField()),
                ('status', models.CharField(choices=[('a', 'Activa'), ('i', 'Inactiva'), ('b', 'Baja'), ('c', 'Cerrada')], default='a', max_length=1)),
                ('tipo_cuenta', models.CharField(choices=[('c', 'Corriente'), ('n', 'Nómina'), ('a', 'Ahorro')], default='c', max_length=1)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asesor', models.ManyToManyField(to='banco.Asesor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('n', 'Pago de Nómina'), ('p', 'Pago a proveedores'), ('r', 'Reembolso de gastos'), ('t', 'Traslado de efectivo entre entidades bancarias')], default='pn', max_length=1)),
                ('cuenta_origen', models.CharField(max_length=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='banco.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_financiamiento', models.CharField(choices=[('p', 'Préstamo'), ('c', 'Crédito')], default='c', max_length=1)),
                ('cantidad_prestamo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cuenta', models.ManyToManyField(to='banco.Cuenta')),
            ],
        ),
    ]
